# Generated by Django 3.2.5 on 2022-05-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_parkinginformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='cameraInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
                ('availableSlots', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
