# Generated by Django 3.2.5 on 2022-05-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220513_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageData',
            fields=[
                ('name', models.CharField(max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capture', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('availableSlots', models.IntegerField(blank=True, null=True)),
            ],
        )
    ]
