# Generated by Django 3.2.5 on 2022-06-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220516_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
