# Generated by Django 3.2.5 on 2022-06-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220606_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='slots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
